### ISSUE TITLE
Send Silently Not Working (Windows, WPF)

### ISSUE THREAD

**Issue by NextAlexM** [ravibpatel/CrashReporter.NET#22]
Startup:

```
        /// <summary>
        /// On Start-up
        /// </summary>
        /// <param name="e">The start-up event arguments.</param>
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
            Application.Current.DispatcherUnhandledException += DispatcherOnUnhandledException;
            TaskScheduler.UnobservedTaskException += TaskSchedulerOnUnobservedTaskException;

            var bootstrapper = new Bootstrapper();
            bootstrapper.Run();
        }
```

Catchers:
```
         /// <summary>
        /// On unobserved task exception with the task scheduler.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="unobservedTaskExceptionEventArgs">The <see cref="UnobservedTaskExceptionEventArgs"/> instance containing the event data.</param>
        private void TaskSchedulerOnUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs unobservedTaskExceptionEventArgs)
        {
            SendReport(unobservedTaskExceptionEventArgs.Exception);
            Environment.Exit(0);
        }

        /// <summary>
        /// On unhandled exception of the dispatcher.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="dispatcherUnhandledExceptionEventArgs">The <see cref="DispatcherUnhandledExceptionEventArgs"/> instance containing the event data.</param>
        private void DispatcherOnUnhandledException(object sender, DispatcherUnhandledExceptionEventArgs dispatcherUnhandledExceptionEventArgs)
        {
            SendReport(dispatcherUnhandledExceptionEventArgs.Exception);
            Environment.Exit(0);
        }

        /// <summary>
        /// On unhandled exception of the current domain.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="unhandledExceptionEventArgs">The <see cref="UnhandledExceptionEventArgs"/> instance containing the event data.</param>
        private static void CurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs unhandledExceptionEventArgs)
        {
            SendReport((Exception)unhandledExceptionEventArgs.ExceptionObject);
            Environment.Exit(0);
        }
```

Sender:
```
        /// <summary>
        /// Sends the crash report.
        /// </summary>
        /// <param name="exception">The exception.</param>
        /// <param name="developerMessage">The developer message.</param>
        /// <param name="silent">if set to <c>true</c> [silent].</param>
        public static void SendReport(Exception exception, string developerMessage = "", bool silent = true)
        {
            var reportCrash = new ReportCrash("REMOVED")
            {
                DeveloperMessage = developerMessage,
                Silent = silent
            };

            reportCrash.Send(exception);
        }
```

Placing a breakpoint in the "SendReport" method and it's hit when a crash occurs.

Setting the variable "silent" to "false" opens the dialog on a crash, sends and receives fine.

Settings the variable "silent" to "true", breakpoint still hits like normal, no report is sent.

Have tried calling `reportCrash.SendSilently(exception);` instead, same result.

Have tried adding "DoctorDumpSettings" to the "ReportCrash":
```
            var reportCrash = new ReportCrash("REMOVED")
            {
                DeveloperMessage = developerMessage,
                Silent = silent,
                DoctorDumpSettings = new DoctorDumpSettings
                {
                    ApplicationID = Guid.Parse("REMOVED"),
                    OpenReportInBrowser = true,
                    SendAnonymousReportSilently = silent
                }
            };
```
The "OpenReportInBrowser" also seems to not work when "reporting silently".

**Comment by ravibpatel** [comment]
I will look into it.

**Comment by ravibpatel** [comment]
I can't reproduce the issue in test projects. Can you provide me example project where I can reproduce the issue?

**Comment by NextAlexM** [comment]
> I can't reproduce the issue in test projects. Can you provide me example project where I can reproduce the issue?

Invited you to a private repo with a project of send silently not working

**Comment by ravibpatel** [comment]
@NextAlexM Can you test the latest version from [here](https://ci.appveyor.com/api/buildjobs/29ot41vfx74dqq05/artifacts/CrashReporter.NET-1.5.7.zip). It should fix the issue.

**Comment by NextAlexM** [comment]
@ravibpatel That's fixed it! Thanks!

**Comment by ravibpatel** [comment]
Updated NuGet package to v1.5.7.

**Comment by bergi9** [comment]
Still not working if only use stmp (no DrDump) because the `stmpClient.SendAsync(message, "CrashReport");` is trying to send asynchronous while the application exits faster than sending.

**Comment by ravibpatel** [comment]
@bergi9 Thanks for reporting. I will look into it asap.

**Comment by bergi9** [comment]
@ravibpatel could you release it on nuget? thank you

**Comment by ravibpatel** [comment]
@bergi9 Can you test out to see if it working fine for you. If it works fine I will release it.

**Comment by ravibpatel** [comment]
@bergi9 You can download the new version from [here](https://ci.appveyor.com/api/buildjobs/0nknwe76u929ixtx/artifacts/CrashReporter.NET-1.5.8.zip).

**Comment by bergi9** [comment]
yep works fine

**Comment by ravibpatel** [comment]
@bergi9 Published NuGet package for v1.5.8. You will be able to download it soon.
